### ISSUE TITLE
ydk-gen cannot generate cpp api if the yang version is 1.1 after Pyang upgrade to 1.7.5

### ISSUE THREAD

**Issue by ankitanni7** [CiscoDevNet/ydk-gen#988] opened 2020-02-24 11:01 UTC
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
Ydk-gen is expected to generate .cpp and .ccp code for yang models with all versions(1.0 and 1.1)

## Current Behavior
Current yang-gen is having pyang version 1.6 which does not support yang-version 1.1. On upgrading to pyang version 1.7.5, pyang is able to validate the yang model but the ydk-gen generates error, it is unable to find import modules.

## Steps to Reproduce
1. Create a yang model with yang-version 1.1
2. Write a json for the above mentioned yang file.
3. Use generate.py with .cpp flag for the json file

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

[root@kontronbng95 ydk-gen]# ./generate.py --cpp --bundle profiles/bundles/dhcp1.json





Traceback (most recent call last):
  File "./generate.py", line 492, in <module>
    output_directory = (generator.generate(options.bundle))
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/__init__.py", line 93, in generate
    return self._generate_bundle(description_file)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/__init__.py", line 128, in _generate_bundle
    packages = self._get_packages(curr_bundle)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/__init__.py", line 203, in _get_packages
    packages = ApiModelBuilder(self.iskeyword, self.language, bundle.name).generate(modules)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/builder/_api_model_builder.py", line 77, in generate
    self._resolve_expanded_cross_references(package)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/builder/_api_model_builder.py", line 154, in _resolve_expanded_cross_references
    self._resolve_expanded_cross_references(owned_element)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/builder/_api_model_builder.py", line 154, in _resolve_expanded_cross_references
    self._resolve_expanded_cross_references(owned_element)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/builder/_api_model_builder.py", line 154, in _resolve_expanded_cross_references
    self._resolve_expanded_cross_references(owned_element)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/builder/_api_model_builder.py", line 154, in _resolve_expanded_cross_references
    self._resolve_expanded_cross_references(owned_element)
  File "/root/ankit/ydk-gen-master/ydk-gen/ydkgen/builder/_api_model_builder.py", line 138, in _resolve_expanded_cross_references
    if not hasattr(identity_ref_type.i_type_spec.base.i_identity, 'i_class'):
AttributeError: 'NoneType' object has no attribute 'i_identity'

```

## System Information

Python version: Python 2.7.5
Operating System: CentOS Linux 7 
Pyang 1.7.5

**Comment by ygorelik** [comment] 2020-02-24 18:13
Duplicate of #801.
Currently there are no resources for this development.

**Closed by ygorelik** 2020-02-24 18:13 UTC
