### ISSUE TITLE
Cisco_IOS_XE_native aaa.group.server error

### ISSUE THREAD

**Issue by nahun** [CiscoDevNet/ydk-gen#690] opened 2018-02-21 02:43 UTC
## Expected Behavior
Output the XML

## Current Behavior
Throws error

## Steps to Reproduce
Run script

## Your Script
```python
from ydk.models.cisco_ios_xe.Cisco_IOS_XE_native import Native
from ydk.providers import CodecServiceProvider
from ydk.services import CodecService
import logging

log = logging.getLogger('ydk')
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
log.addHandler(handler)

native = Native()
tac = native.aaa.group.server.Tacacsplus()
tac.name = "TEST"
tac_server = tac.ServerPrivate()
tac_server.name = "1.2.3.4"
k = tac_server.Key()
k.encryption = 7
k.key = 'testkey'
tac_server.key = k
tac.server_private.append(tac_server)
native.aaa.group.server.tacacsplus.append(tac)

provider = CodecServiceProvider(type="xml")
codec = CodecService()
xml_string = codec.encode(provider, native)
print xml_string
```

## Logs
```python
<snip>
Creating node 'Cisco-IOS-XE-aaa:group' with value ''
Current path: /Cisco-IOS-XE-native:native/aaa
Top container path: Cisco-IOS-XE-native:native
Looking to populate schemas for Cisco-IOS-XE-aaa:group
Ready to populate schemas for Cisco-IOS-XE-aaa:group
Getting new modules for Cisco-IOS-XE-aaa:group
Getting new modules for Cisco-IOS-XE-aaa:group
Module 'Cisco-IOS-XE-aaa' Revision ''
Cache hit Module 'Cisco-IOS-XE-aaa' Revision ''
Getting child schema with path 'Cisco-IOS-XE-aaa:group' in aaa
Getting data nodes with path 'Cisco-IOS-XE-aaa:group'
Creating new data path 'Cisco-IOS-XE-aaa:group' with value '' in 'aaa'
Leaf count: 0
Children count for: Cisco-IOS-XE-aaa:group : 1
==================
Looking at child 'server': server
Populating schemas for server
Couldn't fetch schema node server!
Traceback (most recent call last):
  File "../testing/ydk-test.py", line 26, in <module>
    xml_string = codec.encode(provider, native)
  File "/home/wheeler/Documents/projects/dmvpn/dmvpn-ansible/local/lib/python2.7/site-packages/ydk/errors/error_handler.py", line 112, in helper
    return func(self, provider, entity, *args, **kwargs)
  File "/home/wheeler/Documents/projects/dmvpn/dmvpn-ansible/local/lib/python2.7/site-packages/ydk/services/codec_service.py", line 74, in encode
    return self._encode(provider, entity_holder, pretty, subtree)
  File "/home/wheeler/Documents/projects/dmvpn/dmvpn-ansible/local/lib/python2.7/site-packages/ydk/services/codec_service.py", line 105, in _encode
    return result
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/wheeler/Documents/projects/dmvpn/dmvpn-ansible/local/lib/python2.7/site-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/home/wheeler/Documents/projects/dmvpn/dmvpn-ansible/local/lib/python2.7/site-packages/ydk/errors/error_handler.py", line 56, in _raise
    raise exc
ydk.errors.YPYCoreError:  Couldn't fetch schema node server
```

## System Information

Python 2.7.12, Ubuntu 16.04 x86_64
Testing against ASR1002-X running 16.7.1, though that doesn't matter for this issue
```
$ pip freeze | grep ydk
ydk==0.7.0
ydk-models-cisco-ios-xe==16.7.1
ydk-models-ietf==0.1.4
ydk-models-openconfig==0.1.4
```

**Comment by abhikeshav** [comment] 2018-02-21 22:39
Unable to reproduce with the code from the `ydk-gen` `master` branch. The encode operation produces the xml as expected.

To install the latest code:

```
pip uninstall ydk -y
git clone https://github.com/ciscodevnet/ydk-gen.git
cd sdk/python/core
python setup.py sdist
pip install dist/ydk-*.tar.gz
```

This code will be part of next ydk release `0.7.1`

**Closed by abhikeshav** 2018-02-21 22:39 UTC
Labels: bug
