### ISSUE TITLE
Directory with a space break ydk-cpp installation

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#328] opened 2016-12-09 23:51 UTC
Directory path with an embedded space need to be escaped:
```
$ make
[  1%] Performing build step for 'project_libnetconf'
gcc: error: Programmability/YDK/github/111pontes/ydk-cpp/core/ydk/build/project_libnetconf/src/project_libnetconf/src: No such file or directory
Makefile:233: recipe for target '.obj/src/callbacks.lo' failed
make[3]: *** [.obj/src/callbacks.lo] Error 1
CMakeFiles/project_libnetconf.dir/build.make:113: recipe for target 'project_libnetconf/src/project_libnetconf-stamp/project_libnetconf-build' failed
make[2]: *** [project_libnetconf/src/project_libnetconf-stamp/project_libnetconf-build] Error 2
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/project_libnetconf.dir/all' failed
make[1]: *** [CMakeFiles/project_libnetconf.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
$ 
```

**Comment by abhikeshav** [comment] 2016-12-10 00:52
Caused by https://github.com/CESNET/libnetconf/issues/249. Waiting for their response

**Comment by abhikeshav** [comment] 2016-12-12 18:21
fixed on our fork https://github.com/abhikeshav/libnetconf/commit/f86f73f227ec5832e43a5f3f0a1e64352ef753dc

**Closed by abhikeshav** 2016-12-12 18:21 UTC
Labels: C++
