### ISSUE TITLE
Cisco_IOS_XR_lpts_lib_cfg : Got segmentation fault while creating CRUD create operation

### ISSUE THREAD

**Issue by mjegathe** [CiscoDevNet/ydk-gen#551] opened 2017-09-14 12:49 UTC
## **Description:**

When i tried to create CRUD create operation for policer_cfg from the below code block got segmentation fault. 
Note: And also if i do CRUD create operation for lpts_cfg RPC is not generated and configuration is not written into router but operation succeeded message alone is came.

## **Code Block:**

def create_lpts_cfg(crud_service, provider):
    lpts_cfg = Cisco_IOS_XR_lpts_lib_cfg.Lpts()
    policer_cfg = lpts_cfg.Ipolicer()
    policer_cfg.enable = Empty()
    flow_cfg = policer_cfg.flows.Flow()
    flow_cfg.flow_type = LptsFlow.igmp
    flow_cfg.rate = 100
    flow_cfg.precedences.precedence.append(LptsPreIFibPrecedenceNumber.routine)
    policer_cfg.flows.flow.append(flow_cfg)
    #pdb.set_trace()
    try:
        crud_service.create(provider, policer_cfg)

## **RPC Error for policer_cfg:**

-bash-4.2$ python2.7 /auto/tftp-pluto/mjegathe/ydk-py/core/samples/lpts_cfg.py --host 10.85.104.17 --port 20901 -u root -p root
Establishing connection with device 10.85.104.17:20901 using ssh :
Path where models are to be downloaded: /users/mjegathe/.ydk/10.85.104.17:20901
Path where models are to be downloaded: /users/mjegathe/.ydk/10.85.104.17:20901
Connected to 10.85.104.17 on port 20901 using ssh
Connected to 10.85.104.17 on port 20901 using ssh
connection established...
Executing CRUD create operation
Executing CRUD create operation
Segmentation fault (core dumped)

**Comment by abhikeshav** [comment] 2017-09-14 22:13
Could not reproduce the segfault. The below script worked fine for me. I had to modify your script a little bit:

```python
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_lpts_lib_cfg    
from ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_pre_ifib_cfg import LptsFlow
from ydk.models.cisco_ios_xr.Cisco_IOS_XR_lpts_pre_ifib_cfg import LptsPreIFibPrecedenceNumber
from ydk.types import Empty

lpts_cfg = Cisco_IOS_XR_lpts_lib_cfg.Lpts()     
lpts_cfg.ipolicer = lpts_cfg.Ipolicer()
lpts_cfg.ipolicer.enable = Empty()
flow_cfg = lpts_cfg.ipolicer.flows.Flow()
flow_cfg.flow_type = LptsFlow.igmp
flow_cfg.rate = 100
flow_cfg.precedences.precedence.append(LptsPreIFibPrecedenceNumber.routine)
lpts_cfg.ipolicer.flows.flow.append(flow_cfg)

crud.create(provider, lpts_cfg)
```

**Comment by mjegathe** [comment] 2017-09-15 04:29
[RPC output for lpts_cfg.txt](https://github.com/CiscoDevNet/ydk-gen/files/1303009/RPC.output.for.lpts_cfg.txt)

**Comment by abhikeshav** [comment] 2017-09-29 17:10
Let me know if this issue persists. Could not reproduce it above. Closing issue for now

**Closed by abhikeshav** 2017-09-29 17:10 UTC
Labels: bug, question
