### ISSUE TITLE
YDK-cpp using ietf yang models: vlan tagging not supported

### ISSUE THREAD

**Issue by vhuertas** [CiscoDevNet/ydk-gen#808] opened 2018-07-11 11:11 UTC
I would like to use ietf yang modems for interface configuration. However, there is no way to specify subinterfaces or the vlan tag associated to an interface. The IETF yang models implemented doesn't seem to include it.

I would like to avoid openconfig models for several reasons and I want to use the cpp api of the IETF bundle. As I said, no vlan subinterfaces are supported.

Is there some workaround in order to specify vlan tag? The only one that comes to mind is to take advantage of the interface name. For example, eth0.30 would mean that the eth0 has a subinterface with vlan tag 30. As the name is not the "elegant" way to specify subinterfaces I wanted to know if there would be some other means to do using ietf bundle.

The other option is to support experimental yang models from ietf which are implemented in yang version 1.1. But this is upto the roadmap of the API and you guys are the only ones who can answer this question.

Thanks.

Regards,

**Comment by abhikeshav** [comment] 2018-09-10 21:28
Solution is to introduce yang 1.1 support

Duplicate of #801

**Closed by abhikeshav** 2018-09-10 21:28 UTC
