### ISSUE TITLE
openconfig_routing_policy: Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE) 

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#540] opened 2017-09-08 18:43 UTC
code block:
==========
```python
def config_bgpdefinedset_extcommunityset(crud_service, provider):
    routing_policy_cfg = openconfig_routing_policy.RoutingPolicy()
    extcommunityset_cfg = routing_policy_cfg.defined_sets.bgp_defined_sets.ext_community_sets.ExtCommunitySet()
    extcommunityset_cfg.ext_community_set_name = 'extcom1'
    extcommunityset_cfg.config.ext_community_member.append('extmember1')
    extcommunityset_cfg.config.ext_community_set_name = 'extcom1'
    routing_policy_cfg.defined_sets.bgp_defined_sets.ext_community_sets.ext_community_set.append(extcommunityset_cfg)
    try:
        crud_service.create(provider, routing_policy_cfg)
        crud_service.read(provider, routing_policy_cfg)
    except YPYError:
        print('An error occurred creating the extcommunityset configuration.')
```
		
RPC error:
=========
```ssh
Executing CRUD create operation
Executing CRUD create operation
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Invalid path: openconfig-bgp-policy:bgp-defined-sets
Invalid path: openconfig-bgp-policy:bgp-defined-sets
An error occurred creating the extcommunityset configuration.

```

**Comment by ylil93** [comment] 2017-09-14 21:30
This has been fixed in the new version. I got no such error running the code snippet

**Closed** 2017-09-14 21:32 UTC
Labels: bug

**Comment by mjegathe** [comment] 2017-09-18 05:16
@ylil93 Can you tell in which version of ydk the issue has been fixed. Because i have faced this issue in ydk 0,6.0.

**Comment by mjegathe** [comment] 2017-09-20 05:19
@ylil93  
**YDK version used to run script:**
-bash-4.2$ pip list | grep ydk
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
ydk (0.6.0)
ydk-models-cisco-ios-xr (6.2.2)
ydk-models-ietf (0.1.3)
ydk-models-oc-srini-optical-amplifier (0.1.0)
ydk-models-openconfig (0.1.3)
ydk-models-Openconfig-Channelmonitor-check (0.1.0)

The same version i have used to run the script and i am getting the error.

**Comment by mjegathe** [comment] 2017-09-22 07:42
@ylil93 Can you cross check once again because i am using the same version of ydk (0.6.0)and openconfig(0.1.3) but i am getting the error.

**Comment by ylil93** [comment] 2017-09-22 16:14
@mjegathe 
I ran the code snippet verbatim in two separate environments and could not reproduce this error. I suggest you double check your installations of ydk and openconfig or reinstall them.

**Comment by mjegathe** [comment] 2017-09-27 09:10
I have installed new version of ydk(0.6.1) and openconfig(0.1.4) and still facing the same issue.

**Comment by ylil93** [comment] 2017-09-27 17:24
It's possible the issue has to do with running on XR. I'll try to reproduce the error on an XR image.
