### ISSUE TITLE
ydk-gen should be a pip install-able package

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#220] opened 2016-08-15 15:26 UTC
`generate.py` would be specified as an `entry_point` under `setup()`

your examples & etc could be delivered and installed as `data_files` under a specified folder under the user's virtual-environment root.

**Comment by abhikeshav** [comment] 2017-01-30 00:56
Duplicate of #70

**Closed by abhikeshav** 2017-01-30 00:56 UTC
Labels: enhancement
